/*
# Create portfolio contact messages table

1. New Tables
- `messages`: stores visitor-submitted contact form messages.
- `id`: UUID primary key generated by the database.
- `name`: visitor name.
- `email`: visitor email address used for replies.
- `subject`: message subject.
- `message`: message body.
- `created_at`: timestamp automatically set when the message is stored.

2. Security
- Row Level Security is enabled on `messages`.
- No public read, update, or delete policies are created.
- The server-side contact route uses the service role to insert validated submissions without exposing that credential to the browser.

3. Important Notes
- This table is intentionally not readable through the public client.
- Contact delivery also depends on the configured SMTP settings in the server environment.
*/

CREATE TABLE IF NOT EXISTS public.messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  subject text NOT NULL,
  message text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
